export {
    CONTACT_ADMISSION_LOW_WATERMARK,
    CONTACT_ADMISSION_MAXIMUM_KEY_PACKAGES,
    CONTACT_ADMISSION_TARGET_KEY_PACKAGES,
    contactSessionDescriptor,
    decodeContactPacket,
    decodeContactSessionDescriptor,
    encodeContactPacket,
    isContactSessionDescriptor,
    validateContactAdmission,
    validateContactProfile,
} from "./impl/contactCodec.js";
export type {
    MurmurContact,
    MurmurContactAdmission,
    MurmurContactAdded,
    MurmurContactPacket,
    MurmurContactProfile,
    MurmurContactProfileValue,
    MurmurContactRemoved,
    MurmurContactRequest,
    MurmurContactRequested,
    MurmurContactUpdated,
    MurmurOutgoingContactRequest,
} from "./types.js";
